## Field Assessment Data from Natura 2000 Habitat Monitoring {#sec-ds-fieldassessments}

Prior to implementing any monitoring measures of the natural environment of Natura 2000 habitats, it is essential to confirm that the expected habitat type is present or absent at the target location.
Part of the MNE project is therefore contribution to existing location evaluation efforts, with the focus on sites selected for abiotic sampling.

Location evaluation activities are partially captured via MNE-specific apps and stored on a database (*cf.* @sec-ds-fieldworkorga: evaluation of habitat type, GRTS cell mapping), 
and partially returned via centralized INBO data collection procedures (e.g. registration of presence of key species).


- Numerical
- New/Primary dataset
- Collection began in 2022
- Expected to include ongoing/continuous data collection and yearly updating of dataset until (at least) 2050.
- Data are updated frequently (e.g. daily) in the production environment such as Inboveg.
- Backup strategy: monthly data dumps to cloud storage such as Google Drive, and to local digital storage (physical hard drives).
- Publishing strategy: releases are made less frequently (e.g. yearly) to Zenodo. This process may be facilitated by GitHub.
- Version control will be implemented continuously in between published releases, using git.
- Related to MHQ (Monitoring of biotic habitat quality).
- Data is collected in conjunction with ANB (Agentschap Natuur en Bos). Related to MHQ.
- Data is publicly owned.
- CC0 usage license.
- Data management responsibilities rest with INBO.

