## Design Attributes and Outcome of Spatiotemporal Sampling {#sec-ds-rep}

Target locations (sample units) are randomly drawn from a dynamic *sampling frame* (@sec-ds-samplingframe) and recurrently visited according to a spatiotemporal revisit design, the "revisit plan" (REP).

The procedure of assembling prior geospatial and ecological knowledge to generate the sampling frame, and the derivation of the REP, generate a number of tables and objects which guide the subsequent field work and data acquisition.
The procedure is complex, yet extensively documented.

:::{.callout-note title="git repository"}
Scripts to generate the REP are publicly available on the git repository <https://github.com/inbo/n2khab-mne-designs>.
:::

Among the results of these scripts are "REP objects", a set of R objects (data frames/"tibbles"), which enable or facilitate downstream processing and are shared internally.


- Numerical
- New/Primary dataset which includes, among other data, the stratum size; sampling weight per site & per observation year; tracks planned sites, planned site visits & site replacements; is created from R functions which draw the sample from the sampling frame.
- Dataset compilation began in 2022.
- Expected to include ongoing/continuous data revision/addition and yearly updating of dataset until (at least) 2050.
- Data are updated frequently (e.g. daily) in relation to the sampling frame; format and workflow TBD (e.g. text format).
- Backup strategy: monthly data dumps to cloud storage such as Google Drive, and to local digital storage (physical hard drives).
- Publishing strategy: releases are made less frequently (e.g. yearly) to Zenodo. This process may be facilitated by GitHub.
- Version control will be implemented continuously in between published releases, using git.
- Data will be uploaded to GitHub; format and workflow TBD.
- Related to MHQ (Monitoring of biotic habitat quality).
- Data management responsibilities rest with INBO.


