## Metadata of in-situ equipment at groundwater sites {#sec-ds-gw-meta}

The WATINA database also provides fields for some relevant, explanatory sample unit attributes.
As a result, it is not necessary to also record that information via the MNE database.
Examples include reference measurements of water levels and diver calibrations, soil drilling profile descriptions, and installation repair and replacement.

This data is generally handled in conjunction with the other WATINA data sets (@sec-ds-gw-levels, @sec-ds-gw-quality).


- Numerical; Text (English)
- Adding new data to an existing dataset (the Watina SQL Server database). Data are updated frequently (e.g. daily).
- Added data is verified.
- Includes properties of in-situ equipment for interpretation & equipment management, such as filter depth and spatial position.
- Collection since 2025; expected to run until at least 2050; carried out exclusively by INBO
- Backup strategy: monthly data dumps to cloud storage such as Google Drive, and to local digital storage (physical hard drives).
- Publishing strategy: planned to be published openly as soon as possible. Releases are made less frequently (e.g. yearly) to Zenodo.
- Expected to include ongoing/continuous data revision/addition and yearly updating of dataset until (at least) 2050.

