# Project Information {#sec-project}

## Project Title {#sec-project-title}

Monitoring Programme for the Natural Environment


## Project Description {#sec-project-description}
`QUESTION` draft - to be proofread


The goal of the Monitoring Programme for the Natural Environment is to monitor the the abiotic environment at the regional level in Flanders. 
The programme aims to determine and monitor the status and trends of environmental pressures in Natura 2000 habitats and regionally important biotopes.
Various environmental pressures, such as eutrophication, acidification, desiccation, pollution, and climate change, have an impact on the quality of nature.
Through the programme, we aim to provide a coherent overview of the various environmental pressures which influence habitats via the five compartments of the natural environment: soil, groundwater, surface water, air, and floodwater.
Monitoring schemes are specifically designed for each combination of pressure and compartment, and schemes are implemented successively (phased roll-out) according to policy priorities.
The programme will provide reliable data about the status and trend of the abiotic context of vulnerable habitats, thereby supporting the planning, evaluation, and adjustment of Flemish nature policy.
We use a statistically profound, robust approach to provide spatially balanced, random samples, we aim to establish efficient GIS data pipelines to support outstanding field work, and we commit to providing high quality and fully transparent research within INBO's Open Science framework.


*(modified from: <https://pureportal.inbo.be/en/organisations/monitoring-programme-for-the-natural-environment>, accessed 25/08/2026)*

## Links {#sec-project-links}

+ <https://pureportal.inbo.be/en/organisations/monitoring-programme-for-the-natural-environment/>

## Project Contact {#sec-project-contact}

See @sec-contact.
