project:
  type: book

book:
  title: "DMP for MNE - Monitoring Programme for the Natural Environment"
  author:

    - name:
        given: Karen
        family: Wuyts
        literal:  Karen Wuyts
      email: karen.wuyts@inbo.be
      orcid: 0000-0002-3371-6828
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels
    - name:
        given: Floris
        family: Vanderhaeghe
        literal: Floris Vanderhaeghe
      email: floris.vanderhaeghe@inbo.be
      orcid: 0000-0002-6378-6229
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels
    - name:
        given: Falk
        family: Mielke
        literal: Falk Mielke
      email: falk.mielke@inbo.be
      orcid: 0000-0003-3229-0981
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels
    - name:
        given: Toon
        family: Westra
        literal: Toon Westra
      email: toon.westra@inbo.be
      orcid: 0000-0003-2478-9459
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels
    - name:
        given: Maria-Rose
        family: Eves Down
        literal: Maria-Rose Eves Down
      email: mariarose.evesdown@inbo.be
      orcid: 0009-0000-9611-3824
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels
  date: "2026-08-21"
  chapters:
    - index.qmd
    - 01_information.qmd
    - 02_datasets.qmd
    - 10_dataset_specificities.qmd
    - 80_integration.qmd
    - 91_interoperability.qmd
    - 92_accessibility.qmd
    - 93_storage.qmd
    - 98_contact.qmd
    - 99_references.qmd

bibliography: references.json

format:
  html:
    theme:
      - cosmo
      - brand
    # title-block-banner: '#C04483'
    email-obfuscation: references
    linkcolor: '#C04483'
    embed-resources: true
  pdf:
    documentclass: scrreprt
    linkcolor: 'inbopink'
    include-in-header:
      text: |
        \usepackage{xcolor}
        \definecolor{inbopink}{HTML}{C04483}
