project:
  type: book

book:
  title: "DMP for MNE - Monitoring Programme for the Natural Environment (v2.0)"
  date: "2026-08-26"

  chapters:
    - index.qmd
    - 10_dmp_information.qmd
    - 20_project_project.qmd
    - 30_data_components.qmd
    - 31_dataset_specifications.qmd
    - 40_integration.qmd
    - 50_interoperability.qmd
    - 51_software_dependencies.qmd
    - 60_accessibility.qmd
    - 70_storage.qmd
    - 80_contact.qmd
    - 90_references.qmd

  author:
    - name:
        given: Karen
        family: Wuyts
        literal:  Karen Wuyts
      email: karen.wuyts@inbo.be
      orcid: 0000-0002-3371-6828
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels
    - name:
        given: Floris
        family: Vanderhaeghe
        literal: Floris Vanderhaeghe
      email: floris.vanderhaeghe@inbo.be
      orcid: 0000-0002-6378-6229
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels
    - name:
        given: Falk
        family: Mielke
        literal: Falk Mielke
      email: falk.mielke@inbo.be
      orcid: 0000-0003-3229-0981
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels
    - name:
        given: Toon
        family: Westra
        literal: Toon Westra
      email: toon.westra@inbo.be
      orcid: 0000-0003-2478-9459
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels
    - name:
        given: Maria-Rose
        family: Eves Down
        literal: Maria-Rose Eves Down
      email: mariarose.evesdown@inbo.be
      orcid: 0009-0000-9611-3824
      affiliations:
        - name: Research Institute for Nature and Forest (INBO)
          city: Brussels

bibliography: references.json

format:
  html:
    theme:
      - cosmo
      - brand
    # title-block-banner: '#C04483'
    email-obfuscation: references
    linkcolor: '#C04483'
  pdf:
    documentclass: scrreprt
    linkcolor: 'inbopink'
    include-in-header:
      text: |
        \usepackage{xcolor}
        \definecolor{inbopink}{HTML}{C04483}
