# Datacomponent(en) {#sec-data}
<!--
Informatie specifiek over de datacomponent(en) die dit DMP beschrijven.
Voor elke datacomponent wordt er nagedacht over formaten, types, opslag, ...

"We spreken over primaire en secundaire data, d.w.z. "nieuwe" data of data die je nieuw zal genereren tijdens dit project, en "oude" data of data die al bestond voor je project, die je zal hergebruiken tijdens dit project.

Voor meer informatie over deze begrippen, zie https://www.open.edu/openlearn/money-business/using-data-aid-organisational-change/content-section-4.1

--------------------------------------------------------------------------------------------------------------------------------------------------------------

Data Component Details
Information specifically about the data component(s) that this DMP describes.
For each data component, information is given about the data types, formats, storage, ...

Here, we discuss primary and secondary data - that is "new" data that will be generated during this project, and "old" data, or data which already existed before this project and that will be used during it.

For more information about these terms, please see https://www.open.edu/openlearn/money-business/using-data-aid-organisational-change/content-section-4.1

-->

## Welke types en formaten van data zullen verzameld, gegenereerd en/of hergebruikt worden? {#sec-data-types}

<!--
Geef een overzicht van de types en formaten van datacomponenten die dit DMP zal beschrijven.
Lijst alle verschillende datacomponenten op die zullen worden gegenereerd of gebruikt. Eenmaal geweten, geef de exacte titel van de bestanden, gepubliceerde dataset of identifier-range van fysieke stalen specimens. Bij bestanden, noteer ook de extensie.

Het kan makkelijker zijn om te werken met nummering: geef elke component een cijfer, en dan kan dit cijfer gebruikt worden doorheen dit DMP om te verwijzen naar de datacomponent. Je zal voorbeelden zien in de 'example answers' vanaf hier.

---------------------------------------------------------

What types and formats of data will the project generate, collect and/or reuse?

List the types and formats of data components that this DMP will describe.
List all of the different data components that will be generated or used. Once known, give the exact title of the files, published dataset or identifier range of physical sample specimens. For files, please also note the extension.


It may be easier to work with numbering- give each component a number, and then this number can be used throughout this DMP. You will see examples in the 'example answer's from this point onwards.


-->

In dit project worden zowel inventarisatiegegevens van oeverplanten (Inventory001.xlsx), veldmetingen van waterabiotiek (waterabio2025011.csv) en gegevens rond landgebruik (gps-data in de collardatabank) ingezameld. Er zal een lijst van vrijwilligers bijgehouden worden (gevoelige info, volunteers3.xlsx) en er zullen rond 25 bodemstallen verzameld.
Deze sectie zal geupdate worden in de loop van het project.

*Alternatieve stijl:*

1. Inventarisatiegegevens van oeverplanten: Inventory001.xlsx
2. Veldmetingen van waterabiotiek: waterabio2025011.csv
3. Gegevens rond landgebruik (gps-data in de collardatabank)
4. Een werklijst met vrijwiliigersgegevens: volunteers3.xlsx (bevat gevoelige info)
5. Bodemstalen (geschat 25)



## Datacomponent(en) Beschrijving - Primaire data {#sec-data-primary}
<!--
Beschrijf alle primaire datacomponenten die behandeld zullen worden in dit DMP. Dit kan gedetailleerd of kort zijn, afhankelijk van het stadium en de complexiteit van het project/data.
Deze vraag gaat over primaire data, dat wil zeggen 'nieuwe' data die gegenereerd wordt door het project. Het is helemaal oké om hier in te vullen wat je verwacht te genereren - als dit later verandert, update dan dit DMP.

Bestaande data die gebruikt wordt kan gespecificeerd worden in de volgende vraag.

---------------------------------------------------------

Q - Data Component Description(s) - Primary data

Describe all the primary data components that will be covered in this DMP. The descriptions can be detailed or brief, depending on the stage and complexity of the project/data.
This question is about primary data, i.e. 'new' data that will be generated by the project. It is completely fine to note what you expect to generate - if this changes later, update this DMP.

Existing data that will be used can be specified in the next question.
-->


### Grondwaterdata voor import in WATINA (2) 
WATINA staat voor “WATer In NAtuur” en is een databank voor hydrologische monitoring in natuurgebieden. In deze online databank kunnen gegevens over waterstanden en de chemische samenstelling van water/grondwater in natuurgebieden ingevoerd en opgevraagd worden.
.csv
Deze dataset is verzameld door vrijwilligers volgens een protocol dat nog niet gepubliceerd is.

### Digitale kaartlaag van pimpernelmus nesten (3)
Deze dataset is gegenereerd door waarnemingen in waarnemingen.be, dataaanvraag N° XXXXX.
.tiff formaat (of vergelijkbaar).



## Datacomponent(en) Beschrijving - Secundaire data {#sec-data-secondary}

<!--
Beschrijf alle secundaire datacomponenten (zowel van interne als externe) die behandeld zullen worden in dit DMP. Vergeet niet om te noteren hoe deze aangesproken of verkregen zal worden.
Deze vraag gaat over secundaire data, dat wil zeggen 'oude' data (zoals eerder verzamelde, gepubliceerde of via derden verkregen data), dat hergebruikt wordt door het project. Geef specifieke links, waar nodig.

---------------------------------------------------------

Q - Data Component Description(s) - Secondary data

Describe all secondary data components (both internal and external) that will be covered in this DMP. Do not forget to note how these will be accessed or obtained.
This question is about secondary data, i.e. 'old' data (such as that which was previously collected, published or received from third parties), that will be reused by the project. Provide specific links, where needed.
-->


(5) Historische data uit de Watina databank 1998-2008
Zal gebruikt worden voor analyses, hiervoor spreken we de databank rechtstreeks aan vanuit R.

(6) Neerslagdata zijn afkomstig van waterinfo.be 1999-2005
Directe links bestaan nog niet en zullen gegeven worden in een toekomstige update tot dit DMP.



## Plaats van de datacomponenten tijdens het project (incl. links)  {#sec-data-location}

<!--
Voor elke (opgesomde) datacomponent, geef ofwel link(s) naar de opslag locatie, manier, documentatie (zoals een readmefile of protocol, gebruikslicentie indien van toepassing) of beschrijf deze kort. De bedoeling is dat een buitenstaander de datacomponent kan begrijpen zonder de auteurs van dit DMP extra vragen te stellen.
Indien ze enkel intern te raadpleegbaar zijn, gelieve dit te noteren. Verder, als je DMP bedoeld is voor openbare publicatie, verwijder dan de interne links (de beschrijving van de links mag blijven staan, maar de links zelf niet). Dit is om te voorkomen dat interne documenten onbedoeld worden gedeeld.

---------------------------------------------------------

Q - Location of the data component(s) during the project (including links)

For each data component listed, either provide link(s) to storage location, manner and documentation (such as a readmefile, protocol or use-license if appropriate) or describe it briefly. The intention is that an outsider can understand the data component without asking the authors of this DMP additional questions.
If they can only be accessed internally, please note this. Furthermore, if your DMP is intended for public publication, please remove the internal links (the descriptions of the links may remain, but the links themselves must be removed). This is to prevent internal documents from being shared unintentionally.
-->


Data van (2) is ook te vinden op: https://watina.inbo.be/
Technische informatie over de watina database is beschikbaar op: https://www.milieuinfo.be/confluence/display/INBODEV/Watina+herwerking
(3) was verzameld volgens de "STAP" protocol, zie https://inbo.github.io/protocols/2011.15/index.html


## Contactpunt(en) voor de datacomponenten {#sec-data-contact}

<!--
Als de contactgegevens voor een of meer INBO-beheerde datacomponenten anders zijn dan die onder "Projectcontact", geef dan de (belangrijkste) contactperso(o)n(en) voor elke data component.
Let op: Zorg dat deze zeker akkoord zijn met het weergeven van hun mailadres en ORCID, des te meer als het DMP wordt gedeeld buiten INBO of wordt gepubliceerd.

---------------------------------------------------------

Q - If applicable Contact(s) for the data component(s)

If the contact details for one or more INBO-managed data components are different from those under "Project Contact", please provide the (main) contact person(s) for each data component.
Please note: Check that all named people consent to have their email and ORCID listen in this DMP, especially if the DMP will be published and/or circulated beyond INBO.
 

Quarto note: you could also reference the DMP contact chapter (@sec-contact).
-->


(3) Amber Break, ORCID 0XXX-XXX-XXX, amber.break@inbo.be
